### ISSUE TITLE
Use Node.js 20

### ISSUE THREAD

**Issue by gergely-xyz** [UnlyEd/github-action-await-vercel#104]
**Is your feature request related to a problem? Please describe.**
Using this action shows deprecation warnings "Node.js 16 actions are deprecated. " on github

**Describe the solution you'd like**
Update to Node.js 20

**Describe alternatives you've considered**
https://github.com/patrickedqvist/wait-for-vercel-preview is a similar action, but it is also still on Node 16

**Additional context**
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by Vadorequest** [comment]
Available in v2.0.0, see https://github.com/UnlyEd/github-action-await-vercel/tags

There should be no breaking changes, but I preferred to play it safe and release it as a new major version.
