### ISSUE TITLE
v1.2.13 seems to be broken

### ISSUE THREAD

**Issue by ismay** [UnlyEd/github-action-await-vercel#38]
**Describe the bug**

v1.2.13 seems to be broken

**To Reproduce**

1. See the update here: https://github.com/ismay/superwolff/pull/283
2. Error happens here: https://github.com/ismay/superwolff/pull/283/checks?check_run_id=3765971318

**Expected behavior**

Before the update the action worked fine for many runs. Now it consistently crashes.

**Screenshots**

<img width="937" alt="Screenshot 2021-10-01 at 12 20 28" src="https://user-images.githubusercontent.com/7355199/135604546-1c395a5e-4164-4bc1-a322-5f4d270a42d3.png">

**Environment (please complete the following information):**
 - Github CI

**Comment by Vadorequest** [comment]
Thanks for the report! We'll take a look ASAP.

**Comment by Demmonius** [comment]
Hi,
Thank you for bringing this information to our attention. Indeed, this crash is due to an oversight on our part and I am sincerely sorry.
I opened a fix #39.

**Comment by ismay** [comment]
One thing I did notice is that the action reported the vercel build as done on a commit with a different hash than the one the CI run was evaluating. CI was running for 6868494, the unlyed action reported the build for 6868494 as done, but it was actually 459ab54 that was done.

Could that be related to these changes or is that something else?

**Comment by Demmonius** [comment]
It looks like the url returned by [vercel-preview-url](https://github.com/ismay/superwolff/runs/3929184588) doesn't return the right preview URL in your case.

**Comment by ismay** [comment]
> It looks like the url returned by [vercel-preview-url](https://github.com/ismay/superwolff/runs/3929184588) doesn't return the right preview URL in your case.

Ah you're right. I'll see what's causing that. Again thanks for the quick fix!
