### ISSUE TITLE
Deprecated features - set-output and node.js 12

### ISSUE THREAD

**Issue by GCyganek** [UnlyEd/github-action-await-vercel#74]
Running your action in my workflow I get these warnings: 

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/39878361/210377247-a89074fd-bc00-49fa-8e5a-80c649626775.png">

According to the links attached to warning, both will throw errors starting in June. Are you planning to fix it?

**Comment by Vadorequest** [comment]
https://github.com/UnlyEd/github-action-await-vercel/pull/77 didn't fully fixed the issue, I guess we use actions that are using node12. We would need to update those, as well.

**Comment by Vadorequest** [comment]
This isn't a small feat, I thought upgrading node.js would be enough (at least for #1), but it isn't.

actions/checkout@v2 still use node12 (see https://github.com/actions/checkout/blob/v2.6.0/.github/workflows/check-dist.yml) so a major upgrade to v3 seems necessary, but major version bumps can lead to other issues 😕

**Comment by Vadorequest** [comment]
Blocking: https://github.com/UnlyEd/github-action-await-vercel/issues/81, cannot update to node16, maintainer hasn't released a node16 version yet. See https://github.com/marvinpinto/actions/issues/543

**Comment by Vadorequest** [comment]
Most of the warnings regarding node have been fixed. 2 dependencies couldn't be updated yet:
- https://github.com/UnlyEd/github-action-await-vercel/issues/82
- https://github.com/UnlyEd/github-action-await-vercel/issues/81

I haven't looked into the other issue (`set-output`), which might be more serious and harder to migrate from.

**Comment by Vadorequest** [comment]
Example of migration (from another repo) :
https://github.com/marvinpinto/actions/pull/546/files

**Comment by GCyganek** [comment]
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/39878361/211368198-ba7ce486-8dc0-407c-818c-a33478bec242.png">

There is still warning for using node.js 12, the warning for set-outputs is gone

**Comment by GCyganek** [comment]
Yes, tested the latest version (v.1.2.38) and no warnings at all :+1: Good job!
